import Head from 'next/head';
import { Inter } from 'next/font/google';
import Banner from '../components/shared/Banner';
import Partner from '../components/apps/Partner';
import { homepage_banner } from '@/constants/Banner';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const item = {
		title: homepage_banner.title,
		description: homepage_banner.description,
		link: homepage_banner.link,
		img: homepage_banner.img,
		alt: homepage_banner.alt,
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://unpkg.com/aos@2.3.1/dist/aos.css"
					rel="stylesheet"
				></link>
			</Head>
			<main>
				<Banner item={item} />
				<Partner />

				<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
			</main>
		</>
	);
}
